### ISSUE TITLE
lot of warnings when installing sc5-styleguide

### ISSUE THREAD

**Issue by hans2103** [shama/grunt-gulp#9]
When I install sc5-styleguide I get a lot of warnings.
How can I solve these warnings? (not very familiar with this stuff yet)

```
$ npm install sc5-styleguide gulp grunt-gulp --save-dev
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated gulp-cssnext@1.0.1: cssnext is now postcss-cssnext. gulp-cssnext is deprecated. Use gulp-postcss instead. See postcss-cssnext migration guide http://cssnext.io/postcss/
npm WARN deprecated cssnext@1.8.4: cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN deprecated lodash@2.4.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
```

**Comment by shama** [comment]
Some times they can be solved by upgrading the packages you're using but each have their own reason. You can use `npm view [package]` to view info about the package and see if there are newer versions. Some would likely require tracking down the github repo and pinging the author about upgrading the dependencies throwing the warning.

**Comment by hans2103** [comment]
when running ```npm ls graceful-fs``` to find out where ```graceful-ls``` I notice that the deprecated version is used in ```gulp```
And ```gulp``` is a dependency of ```sc5-styleguide```

```
+-- gulp@3.9.1
| `-- vinyl-fs@0.3.14
|   `-- graceful-fs@3.0.8 
```

Can I upgrade the dependencies used by Gulp?

**Comment by shama** [comment]
You can try `npm cache clean && rm -rf node_modules && npm i` to ensure you're getting all the latest tagged dependencies (as some stale ones might be getting cached on your machine).

The maintainer of a package determines the dependencies that are compatible. For instance in the `package.json` if you see `3.0.8` it means it's only compatible with that specific version. If you see `^3.0.8` it means its compatible up to `4.0.0` and an end user clearing their cache and installing will get the latest compatible version. See more here: https://docs.npmjs.com/getting-started/semantic-versioning

Also not all warnings are bad. Some may be because of security issues and some are just a maintainer no longer wanting to support some code but it still works fine. It depends on each package.
